name: flutter_wanandroid
description: Flutterç‰ˆç©Android

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.7.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  english_words: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/lake.jpg
